      - name: Repository Dispatch
        uses: CriticalNoob02/Projeto_Integrador_pt1
        with:
          token: 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
          repository: CriticalNoob02/Cypress-Zeus
          event-type: Test_CI